import React from "react";
import Head from "../../node_modules/next/head";
import NavBar from '../NavBar/NavBar'

const MainLayout = ({ children }) => {
  return (
    <div className={'container'}>
      <Head>
        <title>Next app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className='main'>{ children }</main>
    </div>
  );
};

export default MainLayout;
